# region API

API_KEY = "vTh6WDXyy9sojFQPT7Q615JX31oEEMGrLAexaadpS4V4vlhVDqqvF3mBwMXmVS8V"
API_SECRET = "nuC2xLmP1tWM8gJg59R5eAi0yJDQjnVST7hH0sSaKrKe4l81UF15pRc3y2UYHA1A"

# endregion

# region Preferences

DEFAULT_STRATEGIES_FOLDER = "strategies"
DEFAULT_RESULTS_PATH = ".results/"
DEFAULT_DELIMITER = ";"
MAX_PROCESSES_NUMBER = 36

# endregion
